- name: Deploy War Files to JBoss
  hosts: target1
  become: yes

  tasks:
    - name: Read configuration from config.yml
      include_vars:
        file: ./config.yml
    
    - name: Include ansible-role-jboss-deploy
      include_role:
        name: ansible-role-jboss-deploy  # Specify the name of the role to include

