- name: Deploy War Files to JBoss
  hosts: target1
  become: yes

  tasks:
    - name: Read configuration from config.yml
      include_vars:
        file: Ansible-2/config.yml
    
    - name: role
      include_role:
        file: Ansible-1/role
