- name: Deploy War Files to JBoss
  hosts: target1
  become: yes

  tasks:
    - name: Read configuration from ansible.cfg
      include_vars:
        file: "{{ GITHUB_WORKSPACE }}/ansible.cfg"

    - name: Include ansible-role-jboss-deploy
      include_role:
        name: ansible-role-jboss-deploy
