- name: Deploy War Files to JBoss
  hosts: target1
  become: yes

  tasks:
    - name: Read configuration from config.yml
      include_vars:
        file: "{{ GITHUB_WORKSPACE }}/config.yml"

    - name: Include ansible-role-jboss-deploy from another repository
      include_role:
        name: ansible-role-jboss-deploy
        tasks_from: tasks
      vars:
        ansible_repo_owner: "dillibabu91GIT"
        ansible_repo_name: "Ansible-1"


