- name: Deploy War Files to JBoss
  hosts: target1
  become: yes
  tasks:
    - name: Read configuration from config.yml
      include_vars:
        file: "{{ GITHUB_WORKSPACE }}/config.yml"

    - name: Include ansible-role-jboss-deploy 
      include_roles:
        name: https://github.com/dillibabu91GIT/ansible-1.git
     
