- name: Deploy War Files to JBoss
  hosts: target1
  become: yes
  tasks:
    - name: Read configuration from config.yml
      include_vars:
        file: "{{ GITHUB_WORKSPACE }}/config.yml"

    - name: Execute ansible1 tasks
      include_tasks: ../../ansible1/main.yml
      vars:
        owner: "{{ owner }}"
        repo: "{{ repo }}"
        branch: "{{ branch }}"
        github_token: "{{ github_token }}"
