- name: Deploy War Files to JBoss
  hosts: target1
  become: yes

  tasks:
    - name: Read configuration from config.yml
      include_vars:
        file: "{{ GITHUB_WORKSPACE }}/config.yml"

    # Debug message to verify config values
    - debug:
        var: jboss_controller
    - debug:
        var: github_token

    - name: Get list of .war files in the GitHub repository
      uri:
        url: "https://api.github.com/repos/{{ owner }}/{{ repo }}/contents?ref={{ branch }}"
        method: GET
        headers:
          Authorization: "token {{ github_token }}"
      register: github_response

    # Debug message to verify GitHub response
    - debug:
        var: github_response

    - name: Download .war files from GitHub repository
      get_url:
        url: "{{ item.download_url }}"
        dest: "/tmp/{{ item.name }}"
        headers:
          Authorization: "token {{ github_token }}"
      loop: "{{ github_response.json | selectattr('name', 'match', '.*\\.war$') | list }}"
      register: download_result

    # Debug message to verify download result
    - debug:
        var: download_result

    - name: Copy .war files to JBoss deployment directory
      ansible.builtin.copy:
        src: "/tmp/{{ item.name }}"
        dest: "/opt/wildfly/standalone/deployments/"
        owner: "wildfly"
        group: "wildfly"
        mode: '0777'
        remote_src: yes  # Copy from Ansible controller
      loop: "{{ github_response.json | selectattr('name', 'match', '.*\\.war$') | list }}"
      register: copy_result

    # Debug message to verify copy result
    - debug:
        var: copy_result

    - name: Reload JBoss to deploy changes
      ansible.builtin.shell:
        cmd: "sh /opt/wildfly/bin/jboss-cli.sh --connect command=:reload"
      register: reload_result

    # Debug message to verify reload result
    - debug:
        var: reload_result
