- name: Deploy War Files to JBoss
  hosts: target1
  become: yes

  tasks:
    - name: Read configuration from config.yml
      include_vars:
        file: "{{ GITHUB_WORKSPACE }}/config.yml"

    - name: Include ansible-role-jboss-deploy from another repository
      include_role:
        name: Ansible-1
      vars:
        roles_path: /path/to/Ansible-1/ansible-role-jboss-deploy
