- name: Get list of .war files in the GitHub repository
  uri:
    url: "https://api.github.com/repos/{{ owner }}/{{ repo }}/contents?ref={{ branch }}"
    method: GET
    headers:
      Authorization: "token {{ github_token }}"
  register: github_response

- name: Download .war files from GitHub repository
  get_url:
    url: "{{ item.download_url }}"
    dest: "/tmp/{{ item.name }}"
    headers:
      Authorization: "token {{ github_token }}"
  loop: "{{ github_response.json | selectattr('name', 'match', '.*\\.war$') | list }}"

- name: Copy .war files to JBoss deployment directory
  ansible.builtin.copy:
    src: "/tmp/{{ item.name }}"
    dest: "/opt/wildfly/standalone/deployments/"
    owner: "wildfly"
    group: "wildfly"
    mode: '0777'
    remote_src: yes  # Copy from Ansible controller
  loop: "{{ github_response.json | selectattr('name', 'match', '.*\\.war$') | list }}"

- name: Reload JBoss to deploy changes
  ansible.builtin.shell:
    cmd: "sh /opt/wildfly/bin/jboss-cli.sh --connect command=:reload"
