name: Deploy JBoss Server

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: list command
        run: |
          ls -al
          pwd
           

      - name: Run Ansible playbook
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"
          #ANSIBLE_CONFIG: "./ansible.cfg"
        run: |
          ansible-playbook -vvv -i inventory.txt main.yml --extra-vars "GITHUB_WORKSPACE=/home/ubuntu/jb/actions-runner/_work/ansible-2/ansible-2"
