name: Deploy War Files

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Run Ansible playbook
        env:
          ANSIBLE_HOST_KEY_CHECKING: "true"
        run: |
          ansible-playbook -i inventory.txt playbook/main.yml
