name: Deploy JBoss Server

on:
 workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Ansible playbook
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"
          ANSIBLE_CONFIG: "./ansible.cfg"  # Path to your ansible.cfg file, if required
          GITHUB_WORKSPACE: ${{ github.workspace }}  # Pass the GitHub workspace directory
        run: |
          ansible-playbook -i inventory.txt playbook/main.yml

