workflow
name: Deploy WAR to JBoss

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'WAR Version to Deploy'
        required: true
        default: '1111'

jobs:
  deploy:
    runs-on:
      group: rakbank-self-hosted-runner
      labels: dehitdevtra1
    steps: 
      - name: Checkout Ansible playbook
        uses: actions/checkout@v2

      - name: Run playbook
        env:
          TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB }}
        run: |
          cd ${{ github.workspace }}
          ansible-playbook -b --extra-vars "target=target_jb war_file_url=https://maven.pkg.github.com/Rakbank-DEH-Onboarding/SMEDigitalBank/com/rakbank/infosys/lib/smedigitalbank/${{ github.event.inputs.version }}/smedigitalbank-${{ github.event.inputs.version }}.war" ./playbook/smedeployment.yml
